backend:
  name: git-gateway #test-repo
  branch: master
media_folder: static/img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Trang chủ'
        name: 'trang-chu'
        file: 'content/index.md'
        fields:
          - label: 'Hero'
            name: 'hero'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Image', name: 'image', widget: 'image' }
          - label: 'Services'
            name: 'services'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - label: 'List Services'
                name: 'listServices'
                widget: list
                fields:
                  - { label: 'Name', name: 'name', widget: 'string' }
                  - { label: 'Link', name: 'link', widget: 'string' }
                  - { label: 'Image', name: 'image', widget: 'image' }
          - label: 'Testimonial'
            name: 'testimonial'
            widget: list
            fields:
              - { label: 'Text', name: 'text', widget: 'text' }
              - { label: 'Author', name: 'author', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }

      - label: 'Giới thiệu'
        name: 'gioi-thieu'
        file: 'content/gioi-thieu.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Text info', name: 'text', widget: 'text' }
          - label: 'Features'
            name: 'features'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Image', name: 'image', widget: 'image' }

  - label: 'Blog'
    name: 'blog'
    folder: 'content/blog'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
